### ISSUE TITLE
Logout functionality isn't working in dashboard ui

### ISSUE THREAD

**Issue by jayasanka-sack** [SustainableEducationFoundation/sef-webapps#23]
**Describe the bug**
When clicking on the logout button it says "Error occurred while trying to logout."

**To Reproduce**
1. Login to dashboard. https://sefglobal.org/dashboard/home
2. Click on the logout button.

**Expected behavior**
Users should log out properly and redirect to the login page.

**Screenshots**
![Screenshot 2019-12-28 at 09 16 19](https://user-images.githubusercontent.com/33048395/71538537-b93c1100-2952-11ea-9349-45ff88003742.jpg)

**Additional context**
The Problem is invoker accepts `GET` request to the `/logout` endpoint.
UI is sending a post request. 
Change the endpoint's method to the `POST` in the invoker.

**Comment by YoshithaRathnayake** [comment]
Shall I work on this ?

**Comment by jayasanka-sack** [comment]
Thanks for your interest, @YoshithaRathnayake. But we no longer maintain this repo.
